#!/usr/bin/env bash
# This is a script that transfer a file to a server using scp

if [ $# -lt 3 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp StrictHostKeyChecking=no -i "$4" "$1" "$3@$2:~/"
fi
