#!/usr/bin/env bash
# This script set a custom header reponse for the nginx server
sudo apt-get update
sudo apt-get -y install nginx
sudo sed -i "11i\ \ \ \tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo echo "Holberton School" | sudo tee /var/www/html/index.html
sudo service nginx restart
