#!/usr/bin/env bash
# This script install and configure the HAproxy program for the load balancer
sudo apt-get update
sudo apt-get install -y haproxy=1.6.\*
echo -e "\nbackend web-backend\n
   \tbalance roundrobin\n
   \tserver 936-web-01 35.231.161.8:80 check\n
   \tserver 936-web-02 35.196.8.154:80 check\n\n
frontend http\n
  \tbind *:80\n
  \tmode http\n
  \tdefault_backend web-backend\n" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
