#!/usr/bin/env bash
# This bash script display different outputs using if statements
ITERATOR=1
while [ $ITERATOR -le 20 ]
do
    echo "$ITERATOR"
    case $ITERATOR in
	4*)
	    echo bad luck from China
	    ;;
	9*)
	    echo bad luck from Japan
	    ;;
	17*)
	    echo bad luck from Italy
	    ;;
    esac
    let ITERATOR=ITERATOR+1
done
