#!/usr/bin/env bash
# This script shows you a clock using a while loop
hour=0
minute=1
while [ $hour -le 12 ]
do
    minute=1
    echo Hour: "$hour"
    while [ $minute -le 59 ]
    do
	echo "$minute"
	let minute=minute+1
    done
    let hour=hour+1
done
