#!/usr/bin/env bash
#This script change the your local address direction
cp /etc/hosts ~/hosts.new
sed -i s/^127.*$/'127.0.0.2 localhost'/ ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts



